

from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Boolean, Text, Enum
from sqlalchemy.sql import func
from app.db.base_class import Base

class MappingDetail(Base):
    __tablename__ = 'mapping_details'
    DetailId = Column(Integer, primary_key=True)
    MappingId = Column(Integer, ForeignKey('mappings.MappingId'), nullable=False)
    ColumnId = Column(Integer, ForeignKey('user_schema_columns.ColumnId'), nullable=False)
    TermId = Column(Integer, ForeignKey('schema_org_terms.TermId'), nullable=False)
    AutoGenerated = Column(Boolean, nullable=False)
    Curated = Column(Boolean, nullable=False)
    Certainty = Column(Enum('High', 'Medium', 'Low'))
    Reasoning = Column(Text)
    CreatedAt = Column(DateTime, server_default=func.now())
    UpdatedAt = Column(DateTime, onupdate=func.now())